version: '3.7'
services:
  minesweeper-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: murah
      POSTGRES_USER: postgres
    user: "${UID}:${GID}"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - backend
  minesweeper:
    container_name: minesweeper-api
    image: rodrigosntg/minesweeper
    depends_on:
      - minesweeper-db
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://minesweeper-db:5432/minesweeper
      - JAVA_OPTS=-Dquarkus.http.host=0.0.0.0
  minesweeper-react-app:
    container_name: minesweeper-web
    image: rodrigosntg/minesweeper-react-app
    depends_on:
      - minesweeper
    ports:
      - "3000:3000"
    networks:
      - backend

    # build: ./minesweeper-react
    # volumes:
    #   - './:/minesweeper-react'
    #   - '/minesweeper-react/node_modules'
    # ports:
    #   - 3000:3000
    # stdin_open: true
    # networks:
    #   - backend
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    # command: npm start

    # container_name: minesweeper-react-app
    # build:
    #   context: .
    #   dockerfile: DockerfileReact
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    # ports:
    #   - 3001:3000
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
  
networks:
    backend:
      name: backend
      driver: bridge
      # ipam:
      #   config:
      #     - subnet: 172.28.0.0/16
      #       gateway: 172.28.0.1
      