version: '3.7'
services:
  minesweeper-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: murah
      POSTGRES_USER: postgres
    user: "${UID}:${GID}"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - backend
  minesweeper:
    image: rodrigosntg/minesweeper
    depends_on:
      - minesweeper-db
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://minesweeper-db:5432/minesweeper
  
networks:
    backend:
      driver: bridge
      